apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-rest-service
  labels:
    app: gs-rest-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gs-rest-service
  template:
    metadata:
      labels:
        app: gs-rest-service
    spec:
      containers:
      - name: gs-rest-service
        image: europe-west1-docker.pkg.dev/onyx-glider-460209-a9/gs-repository/gs-rest-service:v0.0.1
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://127.0.0.1:3306/service-db
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password

      - name: cloudsql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
        args:
          [
            "--private-ip",
            "--structured-logs",
            "--credentials-file=/secrets/key.json",
            "--port=3306",
            "YOUR_PROJECT_ID:REGION:INSTANCE_ID"
          ]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets
          readOnly: true
        

      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-sa-credentials