apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-rest-service
  labels:
    app: gs-rest-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gs-rest-service
  template:
    metadata:
      labels:
        app: gs-rest-service
    spec:
      containers:
      - name: gs-rest-service
        image: europe-west1-docker.pkg.dev/onyx-glider-460209-a9/gs-repository/gs-rest-service:v0.0.1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
#        env:
#        - name: SPRING_PROFILES_ACTIVE
#          value: prod
#        - name: DATASOURCE_URL
#          value: jdbc:mysql://127.0.0.1:3306/service-db
#        - name: DATASOURCE_USERNAME
#          valueFrom:
#            secretKeyRef:
#              name: db-credentials
#              key: username
#        - name: DATASOURCE_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: db-credentials
#              key: password